= 예외 처리

[source, python]
----
try:
    with open("나그.txt", mode="r", encoding="UTF-8") as file:
        print(file.read())
except FileNotFoundError as e:
    print(e)
----

---

사용자는 응용 프로그램을 실행하는 과정에서 기대하기 어려운 응답을 입력하거나 존재하지 않는 파일을 호출할 수 있습니다. 오류 가능성은 무한합니다. 응용 프로그램은 사용자가 발생시킬 수 있는 예기치 않은 상황을 처리할 수 있어야 합니다. 아무리 많은 오류 검사를 코드에 추가하더라도 응용 프로그램에서는 언제나 오류가 발생할 수 있어야 합니다.

Python 응용 프로그램에서 실행 오류(Runtime error)가 발생하면 에러(Error)가 발생합니다. Python 에서는 위의 코드처럼 try-except 구문을 사용하여 예외를 처리할 수 있습니다. 응용 프로그램의 try 절 내에 있는 구문이 실행 과정에서 예외를 발생하면 실행은 exception 절로 전송됩니다.

Error 객체의 정보 또는 strerror등의 속성을 사용하여 발생한 예외에 대한 정보를 알 수 있습니다. 위의 소스를 컴파일하고 파라미터 없이 실행하면 아래와 같이 런타임 오류가 처리됩니다.

----
[Errno 2] No such file or directory: '나그.txt'
----

https://wikidocs.net/16060

https://docs.python.org/ko/3/tutorial/errors.html